# Run the object position server container.
# (c) 2018-2023 Tim Molteno (tim@elec.ac.nz)
# License GPL v3

services:
    object_position_server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8876:8876
        restart: unless-stopped
        volumes:
            - ~/catalog_cache:/app/orbit_data
            - ./app:/app/app
        command:
            [
                "uvicorn",
                "main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8876",
                "--loop",
                "uvloop",
                "--access-log",
                "--reload",
                "--workers",
                "1",
            ]
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "1m"
        networks:
            - caddy

networks:
    caddy:
        external: true
        name: caddy_caddy

